In [1]:
from fetch_stock_data import collect_eval_data
import numpy as np
from stock_model_trainer import StockModelEvaluator

# Dummy Example
Here we will just random noise to the eval data. In practice, the predictions would be generated by a stock prediction model.

## Create a synthetic set of stock predictions

In [2]:
eval_data = collect_eval_data()
eval_data.head()

/Users/williamlusty/Documents/GitHub/CS7643-Final-Project/fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed

Ticker            AAPL          BA         JPM         UNH         XOM
Date
2024-11-01  221.662506  154.589996  218.318420  555.512451  109.976837
2024-11-04  220.767532  155.070007  215.223923  545.930237  113.478508
2024-11-05  222.199478  151.000000  216.898499  554.993652  113.813354
2024-11-06  221.473557  147.160004  241.938400  584.024048  115.765099
2024-11-07  226.206924  150.979996  231.479828  592.598145  115.908607

In [3]:
# preds would normally come from a deep forecasting model
preds = eval_data + np.random.normal(size=eval_data.shape)
preds.head()

Ticker            AAPL          BA         JPM         UNH         XOM
Date
2024-11-01  221.516378  155.031418  218.912521  556.494709  109.616224
2024-11-04  220.788813  153.989171  215.179282  546.483822  112.542831
2024-11-05  222.456962  150.389739  215.608228  554.269472  113.130679
2024-11-06  221.957908  147.759525  241.472378  583.402918  115.806962
2024-11-07  227.819130  151.324698  229.674808  592.305671  116.035888

## Call the StockModelEvaluator 
All we have to feed are the predictions and the function will independently access the eval dataset and return metrics

In [4]:
evaluator = StockModelEvaluator()
evaluator.eval(preds)

/Users/williamlusty/Documents/GitHub/CS7643-Final-Project/fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed

{'per_stock_mse': {'AAPL_MSE': 1.0232745197414503,
  'BA_MSE': 0.9513586073421939,
  'JPM_MSE': 1.0568860255825596,
  'UNH_MSE': 0.824715090295197,
  'XOM_MSE': 0.9826425769103949},
 'per_stock_smape': {'AAPL_MSE': 0.3617971580178788,
  'BA_MSE': 0.4101730569529071,
  'JPM_MSE': 0.3063781824729301,
  'UNH_MSE': 0.1894863105853216,
  'XOM_MSE': 0.726580407869071},
 'average_smape': 0.3988830231796217}